# PyTorch

PyTorch is an open-source deep learning library, originally developed by Meta Platforms and currently developed with support from the Linux Foundation. The successor to Torch, PyTorch provides a high-level API that builds upon optimised, low-level implementations of deep learning algorithms and architectures, such as the **Transformer**, or **SGD**.

In [3]:
import torch

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [4]:
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is a shorthand for `4.0`. It is used to indicate to Python (and PyTorch) that you want to create a floating-point number. We can verify this by checking the `dtype` attribute of our tensor.

In [5]:
t1.dtype

torch.float32

Let's try creating more complex tensors.

In [6]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [7]:
# Matrix
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
# 3-dimensional array
t4 = torch.tensor([[[11, 12, 13], [14, 15, 16]], [[17, 18, 19], [20, 21, 22]]])
t4

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])

Tensors can have any number of dimensions and different length along each dimension. We can inspect the length along each dimension by using the `.shape` property of the tensor.

As a rule of thumb, to count the `dimesion` of a tensor start by picking up the *bracket* where the **tensor begins** and then **count the elements** in those brackets that will become the **length** of your first dimension to determine other dimensions and their respective lengths repeat the same process for inner brackets.

For example to count for `t4`:
- Inside the first bracket there are `2` elements so the first dimension becomes `2`
- Inside the second bracket there are `2` elements so the second dimension becomes `2`
- Inside the third bracket there are `3` elements so the third dimension becomes `3`

So, `t4.shape` should be `(2, 2, 3)`, let's check.

In [9]:
t4.shape

torch.Size([2, 2, 3])

### Operations and Gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [10]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We have created three tensors: `x`, `w`, `b`, all numbers. `w` and `b` have additional parameter `requires_grad` which is set to `True`. We'll se what that does in a moment.

Let's create a new tensor `y` by combining these tensors.

In [11]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch unique is the ability to automatically compute the derivate of `y` w.r.t the tensors that have `requires_grad` set to `True`. This feature of PyTorch is called *autograd* (automatic gradients).

To compute the derivates, we can invoke `.backward()` method on our `y`.

In [12]:
y.backward()

The derivative of `y` w.r.t the input tensors are stored in the `.grad` property of the respective input tensors.

In [13]:
print("dy/dx", x.grad)
print("dy/dw", w.grad)
print("dy/db", b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


As expected, $\frac{dy}{dx}$ has the same value as `x` i.e., `3`, and $\frac{dy}{db}$ has the value `1`. Note that $\frac{dy}{dx}$ is `None` because `x` doesn't have `requires_grad` set to `True`.

The "grad" in here is short for *gradient*, which is another term for derivative. The term *gradient* is primarily used when dealing with **vectors** and **metrices**.

### Functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. Let's look at some examples.

#### torch.full()

Create a tensor with a fixed value for every element.

In [21]:
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

#### torch.cat()

Concatenate two tensors with compatible shapes using [`torch.cat()`](https://docs.pytorch.org/docs/2.13/generated/torch.cat.html#torch-cat). By default it concatenates along the `0` dimension.

In [23]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

#### torch.sin()

Compute trignometric sine of each element of a tensor.

In [24]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

#### torch.reshape()

Change the view of the underlying tensor using [`torch.reshape()`](https://docs.pytorch.org/docs/2.13/generated/torch.reshape.html#torch-reshape).

In [25]:
t9 = torch.reshape(t8, (3, 2, 2))
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

#### torch.squeeze() vs torch.unsqueeze()

`unsqueeze()` "adds" a superficial `1` dimension to tensor (at the specified dimension), while `squeeze()` removes all superficial `1` dimensions from tensor.

A `1` dimension is superficial in the sense that it does not add any more elements to the tensor than would be there without it.

<div align="center">
<img src="../../../static/images/squeeze_vs_unsqueeze_2d.png">
</div>

`unsqueeze()` is useful for providing single sample to the network (which requires first dimension to be batch), for images it would be:

In [26]:
t10 = torch.randn(3, 32, 32)
t10.shape

torch.Size([3, 32, 32])

In [27]:
t11 = t10.unsqueeze(dim=0)
t11.shape

torch.Size([1, 3, 32, 32])

And you can use `squeeze()` to squeeze out the extra superficial dimension from the unsqueezed tensor.

> **Note:** `squeeze()` only removes the dimension that has a size of `1` using `squeeze()` on the original image tensor will not change the shape of the tensor.

`squeeze` will squeeze out the superficial dimension in `t11`.

In [30]:
t12 = t11.squeeze(dim=0)
t12.shape

torch.Size([3, 32, 32])

`squeeze` will not do anything since there's no superficial dimension in `t10`.

In [37]:
t13 = t10.squeeze(dim=0)
t13.shape

torch.Size([3, 32, 32])

#### torch.from_numpy

Create a [`Tensor`](https://docs.pytorch.org/docs/2.13/tensors.html#torch.Tensor) from a [`numpy.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray).

In [32]:
import numpy as np

In [34]:
arr = np.array([1., 2., 3.])
t14 = torch.from_numpy(arr)
t14

tensor([1., 2., 3.], dtype=torch.float64)

And then after performing GPU-bound operations on `t14` you can also get your `numpy.array` back by calling `.numpy()` on a `Tensor`.

In [35]:
t14.numpy()

array([1., 2., 3.])

You can see the type is `array` whereas previously the type was `tensor`.